@startuml
class sk.uniza.fri.suradnice.Suradnice {
- int x
- int y
+ int getX()
+ int getY()
}
class sk.uniza.fri.suradnice.RandSuradnice {
}


sk.uniza.fri.suradnice.Suradnice <|-- sk.uniza.fri.suradnice.RandSuradnice
@enduml